- name: Installing Webserver on Debian
  apt: name=apache2 update_cache=yes state=present
  when: ansible_os_family == "Debian"
  notify:
    - Restart Apache 1234    
#    changed_when: true

- name: Installing Webserver on RedHat
  yum: name=httpd update_cache=yes state=present
  when: ansible_os_family == "RedHat"
  notify:
    - Restart Apache 5678
#    changed_when: true

#- name: Change Website
#  template:
#      src: index.j2
#      dest: /var/www/html/index.html

