---
- hosts: webservers
  vars:
    my_name: Sreeprakash
  tasks:
  - name: Installing Webserver on Debian
    apt: name=apache2 update_cache=yes state=present
    when: ansible_os_family == "Debian"
    notify:
    - Restart Apache 1234    
    changed_when: true

  - name: Installing Webserver on RedHat
    yum: name=httpd update_cache=yes state=present
    when: ansible_os_family == "RedHat"
    notify:
    - Restart Apache 5678
    changed_when: true

  - name: Change Website
    copy:
      content: 'Hello from {{ my_name }} - {{ ansible_os_family }}'
      dest: /var/www/html/index.html

  handlers:
  - name: Restart Apache 1234
    service: name=apache2 state=restarted
#    when: ansible_os_family == "Debian"

  - name: Restart Apache 5678
    service: name=httpd state=restarted
#    when: ansible_os_family == "RedHat"


